name: Shared CI

on:
  pull_request:
    paths:
      - 'shared/**'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  environment_fields_setup:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add TMDB Key
        env:
          BASEURL: ${{ secrets.TMDB_API_KEY }}
        run: echo TMDB_API_KEY="$TMDB_API_KEY" > ./gradle.properties

  test:
    needs: environment_fields_setup
    name: Run all Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build with Gradle
        run: ./gradlew build
      - name: Unit tests
        run: bash ./gradlew testDebugUnitTest